import { getGaOverview } from "@/lib/ga";
import { getGscOpportunityQueue, getGscOverview } from "@/lib/gsc";
import { prisma } from "@/lib/prisma";
import { isTelegramConfigured, sendTelegramMessage } from "@/lib/telegram";
import { env } from "@/lib/env";

const REPORT_TIMEZONE = "Asia/Taipei";
const REPORT_HOUR = 8;

type DailyReportMode = "scheduled" | "force";

function getLocalParts(date: Date, timeZone = REPORT_TIMEZONE) {
  const formatter = new Intl.DateTimeFormat("en-CA", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false
  });
  const parts = formatter.formatToParts(date);
  const pick = (type: Intl.DateTimeFormatPartTypes) => Number(parts.find((part) => part.type === type)?.value ?? "0");

  return {
    year: pick("year"),
    month: pick("month"),
    day: pick("day"),
    hour: pick("hour"),
    minute: pick("minute")
  };
}

function getLocalDateKey(date: Date, timeZone = REPORT_TIMEZONE) {
  const parts = getLocalParts(date, timeZone);
  return `${parts.year}-${String(parts.month).padStart(2, "0")}-${String(parts.day).padStart(2, "0")}`;
}

function getLocalDayUtcRange(date: Date, timeZone = REPORT_TIMEZONE) {
  const parts = getLocalParts(date, timeZone);
  const startUtc = new Date(Date.UTC(parts.year, parts.month - 1, parts.day, -8, 0, 0, 0));
  const endUtc = new Date(startUtc.getTime() + 24 * 60 * 60 * 1000);
  return { startUtc, endUtc };
}

function isDailyReportDue(date: Date, timeZone = REPORT_TIMEZONE) {
  const parts = getLocalParts(date, timeZone);
  return parts.hour >= REPORT_HOUR;
}

function formatPercent(value: number) {
  return `${(value * 100).toFixed(value >= 0.1 ? 0 : 1)}%`;
}

function shortNumber(value: number) {
  if (value >= 1_000_000) {
    return `${(value / 1_000_000).toFixed(1)}M`;
  }
  if (value >= 1_000) {
    return `${(value / 1_000).toFixed(1)}K`;
  }
  return String(value);
}

function compactDetail(detail?: string | null, max = 110) {
  const normalized = (detail ?? "").replace(/\s+/g, " ").trim();
  if (!normalized) {
    return "";
  }
  return normalized.length > max ? `${normalized.slice(0, max - 1)}…` : normalized;
}

export async function runDailyOpsDigest(now = new Date(), mode: DailyReportMode = "scheduled") {
  if (!isTelegramConfigured()) {
    return {
      ok: false,
      status: "skipped" as const,
      reason: "telegram_not_configured",
      message: "Telegram 尚未設定，暫時不發每日日報。"
    };
  }

  if (mode === "scheduled" && !isDailyReportDue(now)) {
    return {
      ok: true,
      status: "skipped" as const,
      reason: "not_due",
      message: "尚未到每日日報時間。"
    };
  }

  const { startUtc, endUtc } = getLocalDayUtcRange(now);
  const dateKey = getLocalDateKey(now);

  const existing = mode === "scheduled"
    ? await prisma.automationLog.findFirst({
        where: {
          actionType: "daily_ops_digest",
          status: "executed",
          executedAt: {
            gte: startUtc,
            lt: endUtc
          }
        }
      })
    : null;

  if (existing) {
    return {
      ok: true,
      status: "skipped" as const,
      reason: "already_sent",
      message: "今天的每日日報已經送出。"
    };
  }

  try {
    const last24h = new Date(now.getTime() - 24 * 60 * 60 * 1000);
    const [settings, logRows, pendingReviewCount, expiringTokenCount, gaResult, gscResult, gscOpportunities] = await Promise.all([
      prisma.appSettings.findFirst(),
      prisma.automationLog.findMany({
        where: {
          executedAt: {
            gte: last24h
          }
        },
        orderBy: {
          executedAt: "desc"
        },
        take: 300
      }),
      prisma.post.count({
        where: {
          account: {
            platform: "threads"
          },
          status: "draft",
          isAutoGenerated: true
        }
      }),
      prisma.platformAccount.count({
        where: {
          platform: "threads",
          isActive: true,
          tokenExpiresAt: {
            lte: new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000)
          }
        }
      }),
      getGaOverview().catch((error) => ({
        configured: false,
        propertyId: "",
        source: "ga4",
        totals: { activeUsers: 0, newUsers: 0, sessions: 0, screenPageViews: 0 },
        topPages: [],
        message: error instanceof Error ? error.message : "GA4 讀取失敗"
      })),
      getGscOverview().catch((error) => ({
        configured: false,
        siteUrl: "",
        source: "gsc",
        totals: { clicks: 0, impressions: 0, ctr: 0, position: 0 },
        topPages: [],
        topQueries: [],
        message: error instanceof Error ? error.message : "GSC 讀取失敗"
      })),
      getGscOpportunityQueue().catch((error) => ({
        configured: false,
        items: [],
        message: error instanceof Error ? error.message : "GSC opportunity 讀取失敗"
      }))
    ]);

    const countLogs = (predicate: (item: (typeof logRows)[number]) => boolean) => logRows.filter(predicate).length;

    const autopilotDrafts = countLogs((item) => item.actionType === "daily_persona_generation" && ["draft", "scheduled", "executed"].includes(item.status));
    const promotedThreads = countLogs((item) => item.actionType === "auto_promote_review_draft" && item.status === "scheduled");
    const publishedThreads = countLogs((item) =>
      ["threads_publish", "threads_scheduled_publish"].includes(item.actionType) &&
      ["published", "executed", "success"].includes(item.status)
    );
    const optimizationDrafts = countLogs((item) => item.actionType === "optimization_flywheel" && ["executed", "scheduled"].includes(item.status));
    const wordpressExpansions = countLogs((item) => item.actionType === "auto_wordpress_expansion" && ["executed", "published"].includes(item.status));
    const seoDrafts = countLogs((item) => item.actionType === "seo_opportunity_draft" && ["review", "draft", "executed"].includes(item.status));
    const seoPublished = countLogs((item) => item.actionType === "seo_opportunity_auto_publish" && ["published", "executed"].includes(item.status));
    const failures = logRows.filter((item) => item.status === "failed");
    const failureCount = failures.length;
    const recentFailure = failures[0];

    const missionLine = settings?.missionTitle?.trim()
      ? `${settings.missionTitle.trim()}｜${settings.missionCurrentValue ?? 0}/${settings.missionTargetValue ?? 0} ${settings.missionUnit?.trim() || "月點擊"}`
      : "目前尚未設定 mission，系統會偏保守地自動運轉。";

    const topGaPage = gaResult.configured && gaResult.topPages.length
      ? `${gaResult.topPages[0].path}｜${shortNumber(gaResult.topPages[0].views)} views`
      : "GA4 尚未提供可讀的主流量頁";
    const topGscQuery = gscResult.configured && gscResult.topQueries.length
      ? `${gscResult.topQueries[0].query}｜${shortNumber(gscResult.topQueries[0].impressions)} imp`
      : "GSC 尚未提供明顯的主關鍵字";
    const topSeoOpportunity = gscOpportunities.configured && gscOpportunities.items.length
      ? `${gscOpportunities.items[0].label}：${gscOpportunities.items[0].query ?? gscOpportunities.items[0].page}`
      : "目前沒有明顯 SEO 機會";

    const interventionLines: string[] = [];
    if (settings?.automationPaused) {
      interventionLines.push("自動化目前被暫停");
    }
    if (pendingReviewCount > 0) {
      interventionLines.push(`待你拍板 ${pendingReviewCount} 篇`);
    }
    if (failureCount > 0) {
      interventionLines.push(`失敗任務 ${failureCount} 筆`);
    }
    if (expiringTokenCount > 0) {
      interventionLines.push(`Threads token 7 天內到期 ${expiringTokenCount} 個`);
    }
    if (!interventionLines.length) {
      interventionLines.push("目前沒有明顯例外，系統可繼續自動運轉");
    }

    const lines = [
      `Social Audio 每日日報｜${dateKey}`,
      "",
      `Mission：${missionLine}`,
      `模式：${settings?.autopilotMode || "near_full_auto"}｜WordPress：${settings?.wordpressPublishMode || "draft_only"}`,
      "",
      "過去 24 小時系統已自行處理：",
      `- AI 自動產文 ${autopilotDrafts} 篇`,
      `- Threads 自動升排程 ${promotedThreads} 篇`,
      `- Threads 已發布 ${publishedThreads} 篇`,
      `- 14 天優化稿 ${optimizationDrafts} 篇`,
      `- WordPress 沉長文 ${wordpressExpansions} 篇`,
      `- SEO 草稿 / 自動發布 ${seoDrafts + seoPublished} 篇`,
      "",
      "流量與搜尋：",
      `- GA4：${shortNumber(gaResult.totals.activeUsers)} active / ${shortNumber(gaResult.totals.sessions)} sessions / ${shortNumber(gaResult.totals.screenPageViews)} views`,
      `- GSC：${shortNumber(gscResult.totals.clicks)} clicks / ${shortNumber(gscResult.totals.impressions)} impressions / CTR ${formatPercent(gscResult.totals.ctr)}`,
      `- 主流量頁：${topGaPage}`,
      `- 主關鍵字：${topGscQuery}`,
      `- 今日 SEO 機會：${topSeoOpportunity}`,
      "",
      "只有這些情況值得你介入：",
      ...interventionLines.map((line) => `- ${line}`)
    ];

    if (recentFailure) {
      lines.push("", `最近失敗：${compactDetail(recentFailure.detail, 140) || recentFailure.actionType}`);
    }

    const baseUrl = env.appBaseUrl();
    const buttons = baseUrl
      ? [
          { text: "PM Ops", url: `${baseUrl}/desk` },
          { text: "Review", url: `${baseUrl}/review` },
          { text: "Ops", url: `${baseUrl}/ops` }
        ]
      : undefined;

    await sendTelegramMessage({
      text: lines.join("\n"),
      buttons
    });

    await prisma.automationLog.create({
      data: {
        actionType: "daily_ops_digest",
        status: "executed",
        detail: `已送出 ${dateKey} 每日日報｜AI ${autopilotDrafts}｜Threads 發布 ${publishedThreads}｜WordPress ${wordpressExpansions}｜例外 ${interventionLines.join(" / ")}`
      }
    });

    return {
      ok: true,
      status: "executed" as const,
      message: `已送出 ${dateKey} 每日日報。`
    };
  } catch (error) {
    const detail = error instanceof Error ? error.message : "Daily ops digest failed";
    await prisma.automationLog.create({
      data: {
        actionType: "daily_ops_digest",
        status: "failed",
        detail
      }
    });

    return {
      ok: false,
      status: "failed" as const,
      message: detail
    };
  }
}
