import { prisma } from "@/lib/prisma";

type TriggerConfig = {
  keyword?: string;
  keywordIds?: string[];
};

type ActionConfig = {
  mode?: "template" | "ai";
  accountId?: string;
  template?: string;
};

function buildReplyText(template: string, match: { authorUsername: string; postText: string }, keyword: string) {
  return template
    .replaceAll("{author}", match.authorUsername)
    .replaceAll("{keyword}", keyword)
    .replaceAll("{post_text}", match.postText.slice(0, 120));
}

export async function evaluateAutomationRules() {
  const settings = await prisma.appSettings.findFirst();

  if (settings?.automationPaused) {
    return {
      evaluated: 0,
      scheduled: 0,
      skipped: 0,
      paused: true
    };
  }

  const rules = await prisma.autoRule.findMany({
    where: {
      isActive: true,
      triggerType: "keyword_match"
    },
    orderBy: {
      createdAt: "asc"
    }
  });

  const matches = await prisma.keywordMatch.findMany({
    where: {
      actionTaken: null
    },
    include: {
      keyword: true
    },
    orderBy: {
      matchedAt: "asc"
    },
    take: 50
  });

  let scheduled = 0;
  let skipped = 0;

  for (const rule of rules) {
    const trigger = JSON.parse(rule.triggerConfig) as TriggerConfig;
    const action = JSON.parse(rule.actionConfig) as ActionConfig;

    if (!action.accountId || !action.template) {
      continue;
    }

    const todayStart = new Date();
    todayStart.setHours(0, 0, 0, 0);

    const executionsToday = await prisma.automationLog.count({
      where: {
        ruleId: rule.id,
        status: {
          in: ["scheduled", "executed"]
        },
        executedAt: {
          gte: todayStart
        }
      }
    });

    if (executionsToday >= rule.dailyLimit) {
      await prisma.automationLog.create({
        data: {
          ruleId: rule.id,
          accountId: action.accountId,
          actionType: rule.actionType,
          status: "skipped",
          detail: `已達每日上限 ${rule.dailyLimit}`
        }
      });
      skipped += 1;
      continue;
    }

    for (const match of matches) {
      const matchedKeyword =
        (trigger.keywordIds?.length && trigger.keywordIds.includes(match.keywordId)) ||
        (trigger.keyword && match.postText.toLowerCase().includes(trigger.keyword.toLowerCase())) ||
        match.keyword.keyword.toLowerCase().includes(trigger.keyword?.toLowerCase() ?? "");

      if (!matchedKeyword) {
        continue;
      }

      const existingLog = await prisma.automationLog.findFirst({
        where: {
          ruleId: rule.id,
          matchId: match.id,
          status: {
            in: ["scheduled", "executed"]
          }
        }
      });

      if (existingLog) {
        skipped += 1;
        continue;
      }

      const delayRange = Math.max(rule.delayMaxSeconds - rule.delayMinSeconds, 0);
      const randomDelay = rule.delayMinSeconds + Math.floor(Math.random() * (delayRange + 1));
      const scheduledAt = new Date(Date.now() + randomDelay * 1000);
      const text = buildReplyText(action.template, match, trigger.keyword ?? match.keyword.keyword);

      const post = await prisma.post.create({
        data: {
          userId: "seed-admin",
          accountId: action.accountId,
          contentType: "text",
          textContent: text,
          status: "scheduled",
          scheduledAt,
          isAutoGenerated: true,
          replyToPostId: match.platformPostId,
          sourceMatchId: match.id
        }
      });

      await prisma.keywordMatch.update({
        where: { id: match.id },
        data: {
          actionTaken: "scheduled_reply",
          actionPostId: post.id
        }
      });

      await prisma.autoRule.update({
        where: { id: rule.id },
        data: {
          executionCount: {
            increment: 1
          },
          lastExecutedAt: new Date()
        }
      });

      await prisma.automationLog.create({
        data: {
          ruleId: rule.id,
          matchId: match.id,
          accountId: action.accountId,
          postId: post.id,
          actionType: rule.actionType,
          status: "scheduled",
          detail: `已建立自動回覆，預計 ${scheduledAt.toLocaleString("zh-TW", { hour12: false })} 執行`
        }
      });

      scheduled += 1;
    }
  }

  return {
    evaluated: rules.length,
    scheduled,
    skipped,
    paused: false
  };
}
