export async function evaluateAutomationRules() {
  const { prisma } = await import("@/lib/prisma");

  const rules = await prisma.autoRule.findMany({
    where: {
      isActive: true,
      triggerType: "keyword_match"
    }
  });

  const matches = await prisma.keywordMatch.findMany({
    where: {
      actionTaken: null
    },
    orderBy: {
      matchedAt: "asc"
    },
    take: 20
  });

  let scheduled = 0;

  for (const rule of rules) {
    const trigger = JSON.parse(rule.triggerConfig) as { keyword?: string };
    const action = JSON.parse(rule.actionConfig) as { accountId?: string; template?: string };

    for (const match of matches) {
      if (trigger.keyword && !match.postText.toLowerCase().includes(trigger.keyword.toLowerCase())) {
        continue;
      }

      if (!action.accountId || !action.template) {
        continue;
      }

      const text = action.template
        .replaceAll("{author}", match.authorUsername)
        .replaceAll("{keyword}", trigger.keyword ?? "")
        .replaceAll("{post_text}", match.postText.slice(0, 120));

      await prisma.post.create({
        data: {
          userId: "seed-admin",
          accountId: action.accountId,
          contentType: "text",
          textContent: text,
          status: "scheduled",
          scheduledAt: new Date(Date.now() + Math.max(rule.delayMinSeconds, 30) * 1000),
          isAutoGenerated: true,
          replyToPostId: match.platformPostId
        }
      });

      await prisma.keywordMatch.update({
        where: { id: match.id },
        data: {
          actionTaken: "replied"
        }
      });

      scheduled += 1;
    }
  }

  return {
    evaluated: rules.length,
    scheduled
  };
}
