import { NextResponse } from "next/server";
import { z } from "zod";

import { rewriteContentWithAi } from "@/lib/ai/gateway";
import { buildEditorialMemoryPrompt, findEditorialPresetBySiteUrl } from "@/lib/content/editorial-presets";
import { buildTemplateHtml, inferWordPressDraftPlanning } from "@/lib/content/wordpress-templates";
import { prisma } from "@/lib/prisma";

const schema = z.object({
  page: z.string().min(1),
  query: z.string().optional(),
  lane: z.enum(["refresh", "expand", "capture"]),
  reason: z.string().min(1),
  action: z.string().min(1)
});

function buildParagraphs(summary: string) {
  return summary
    .split(/(?<=[。！？.!?])\s+/)
    .map((line) => line.trim())
    .filter(Boolean)
    .slice(0, 8);
}

export async function POST(request: Request) {
  try {
    const payload = schema.parse(await request.json());
    const user = await prisma.user.upsert({
      where: { id: "seed-admin" },
      update: {},
      create: {
        id: "seed-admin",
        name: "Admin"
      }
    });

    const [settings, wordpressAccount] = await Promise.all([
      prisma.appSettings.findFirst(),
      prisma.platformAccount.findFirst({
        where: {
          userId: user.id,
          platform: "wordpress",
          isActive: true
        },
        orderBy: [{ lastSyncedAt: "desc" }, { createdAt: "desc" }]
      })
    ]);

    if (!wordpressAccount) {
      return NextResponse.json({ ok: false, message: "目前找不到可用的 WordPress 帳號。" }, { status: 400 });
    }

    const titleSeed = payload.query?.trim() || payload.page.trim();
    const sourceBrief = [
      `目前這個搜尋機會頁：${payload.page}`,
      payload.query ? `對應查詢：${payload.query}` : "",
      `系統判定原因：${payload.reason}`,
      `建議動作：${payload.action}`,
      payload.lane === "refresh"
        ? "請優先產出一篇適合更新既有 WordPress 文章的優化稿，偏向 title / desc / CTA / 開頭重寫與段落重組。"
        : payload.lane === "expand"
          ? "請產出一篇適合加長、補 FAQ、補案例與內鏈的 WordPress 優化稿，偏向 SEO 延伸。"
          : "請產出一篇適合新增或重寫承接搜尋意圖的 WordPress 題目稿。"
    ]
      .filter(Boolean)
      .join("\n");

    const siteUrl = wordpressAccount.platformUserId;
    const preset = findEditorialPresetBySiteUrl(siteUrl);
    const personaPrompt =
      buildEditorialMemoryPrompt({
        siteUrl,
        globalPersonaPrompt: settings?.globalPersonaPrompt,
        writingStyleProfile: settings?.writingStyleProfile,
        affiliateLinkPolicy: settings?.affiliateLinkPolicy
      }) || "用冷靜、有觀點、像內容策略師一樣的語氣，幫我把搜尋機會改寫成可更新的長文內容。";
    const preferredProvider = (settings?.aiProvider?.trim() as "auto" | "gemini" | "claude" | "openai" | undefined) ?? "auto";
    const aiResult = await rewriteContentWithAi({
      title: titleSeed,
      rawText: sourceBrief,
      personaPrompt,
      tone: settings?.defaultTone?.trim() || preset?.defaultTone || "sharp-observer",
      siteUrl,
      wordpressTemplate: payload.lane === "expand" ? "case-study" : "opinion",
      preferredProvider
    });

    const planning = inferWordPressDraftPlanning({
      title: aiResult.wordpressTitle || `${titleSeed}｜SEO 優化稿`,
      summary: aiResult.summary,
      templateId: payload.lane === "expand" ? "case-study" : "opinion"
    });
    const paragraphs = buildParagraphs(aiResult.summary);
    const points = paragraphs.slice(0, 3);
    const html =
      aiResult.wordpressHtml ||
      buildTemplateHtml({
        templateId: payload.lane === "expand" ? "case-study" : "opinion",
        title: aiResult.wordpressTitle || `${titleSeed}｜SEO 優化稿`,
        summary: aiResult.summary,
        paragraphs,
        points,
        affiliatePolicy: settings?.affiliateLinkPolicy?.trim() || "",
        personaPrompt,
        affiliateLibrary: {
          primary: settings?.affiliateBlockPrimary?.trim() || "",
          secondary: settings?.affiliateBlockSecondary?.trim() || "",
          disclosure: settings?.affiliateDisclosure?.trim() || "",
          cta: settings?.affiliateCta?.trim() || ""
        },
        planning
      });

    const post = await prisma.post.create({
      data: {
        userId: user.id,
        accountId: wordpressAccount.id,
        contentType: "text",
        title: aiResult.wordpressTitle || `${titleSeed}｜SEO 優化稿`,
        textContent: aiResult.wordpressExcerpt || aiResult.summary.slice(0, 180),
        htmlContent: html,
        excerpt: `${payload.reason}｜${payload.action}`,
        categories: JSON.stringify(["seo-growth", planning.pillar, planning.contentType]),
        tags: JSON.stringify([payload.lane, "gsc-opportunity", ...(payload.query ? [payload.query] : [])]),
        topicTag: "seo-opportunity",
        status: "draft",
        isAutoGenerated: true
      }
    });

    return NextResponse.json({
      ok: true,
      postId: post.id,
      title: post.title,
      message: "已根據 Search Console 機會建立 WordPress SEO 優化稿。"
    });
  } catch (error) {
    return NextResponse.json(
      {
        ok: false,
        message: error instanceof Error ? error.message : "建立 SEO 優化稿失敗"
      },
      { status: 400 }
    );
  }
}
