import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const user = await prisma.user.upsert({
    where: { id: "seed-admin" },
    update: {},
    create: {
      id: "seed-admin",
      name: "Admin"
    }
  });

  const account = await prisma.platformAccount.upsert({
    where: {
      platform_platformUserId: {
        platform: "threads",
        platformUserId: "demo-threads-user"
      }
    },
    update: {},
    create: {
      userId: user.id,
      platform: "threads",
      platformUserId: "demo-threads-user",
      platformUsername: "demo_threads",
      profilePictureUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      accessToken: "encrypted-demo-token",
      tokenType: "long_lived",
      tokenExpiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45)
    }
  });

  await prisma.metricsSnapshot.create({
    data: {
      accountId: account.id,
      followerCount: 1840,
      totalViews: 23200,
      totalLikes: 1690,
      totalReplies: 143,
      totalReposts: 62,
      totalQuotes: 19
    }
  });

  const keyword = await prisma.keyword.create({
    data: {
      userId: user.id,
      keyword: "social audio",
      matchMode: "contains"
    }
  });

  await prisma.keywordMatch.create({
    data: {
      keywordId: keyword.id,
      accountId: account.id,
      platformPostId: "reply-1",
      sourcePostId: "thread-1",
      authorUsername: "trend_watcher",
      postText: "這個 social audio 類型最近很多人在討論",
      actionTaken: "replied"
    }
  });

  await prisma.autoRule.create({
    data: {
      userId: user.id,
      name: "Keyword reply starter",
      triggerType: "keyword_match",
      triggerConfig: JSON.stringify({ keywordIds: [keyword.id] }),
      actionType: "reply",
      actionConfig: JSON.stringify({ mode: "template", accountId: account.id, template: "謝謝 {author}，我們也在觀察 {keyword}。" })
    }
  });

  await prisma.appSettings.upsert({
    where: { id: "seed-settings" },
    update: {},
    create: {
      id: "seed-settings",
      automationPaused: false,
      keywordScanPaused: false
    }
  });

  const post = await prisma.post.upsert({
    where: { id: "seed-post-1" },
    update: {},
    create: {
      id: "seed-post-1",
      userId: user.id,
      accountId: account.id,
      contentType: "thread",
      title: "我把 AI 內容流程拆成四層後，長文終於穩定日更",
      textContent: "不是我突然會寫，是我把語料、素材、題目、學習規則都落進同一條管線。",
      status: "published",
      topicTag: "AI 內容系統",
      isAutoGenerated: true,
      publishedAt: new Date()
    }
  });

  await prisma.voiceSnippet.upsert({
    where: { id: "voice-1" },
    update: {},
    create: {
      id: "voice-1",
      userId: user.id,
      accountId: account.id,
      source: "x-thread",
      personaId: "founder-voice",
      text: "我說話習慣先下結論，再補理由，而且盡量拿真實數字當錨點。",
      topicTags: ["寫作風格", "內容系統"],
      toneTags: ["直接", "數據導向"]
    }
  });

  await prisma.voiceSnippet.upsert({
    where: { id: "voice-2" },
    update: {},
    create: {
      id: "voice-2",
      userId: user.id,
      accountId: account.id,
      source: "chat-log",
      personaId: "founder-voice",
      text: "我不太用雞湯收尾，通常會留一個可操作的結論讓人拿去用。",
      topicTags: ["寫作風格"],
      toneTags: ["務實", "聊天感"]
    }
  });

  await prisma.styleGuide.upsert({
    where: { id: "style-guide-1" },
    update: {},
    create: {
      id: "style-guide-1",
      userId: user.id,
      accountId: account.id,
      personaId: "founder-voice",
      title: "創作者長文 Style Pack",
      summary: "先下判斷，再用數字與案例補強。少用形容詞，多用已驗證路徑。",
      coreSequence: "結論 -> 證據 -> 可複製做法",
      preferredDevices: ["具體數字", "跨產業類比", "經驗拆解"],
      bannedPatterns: ["賦能", "你一定要", "真正厲害的人都在"],
      evidenceSnippetIds: ["voice-1", "voice-2"]
    }
  });

  await prisma.styleRule.upsert({
    where: { id: "style-rule-1" },
    update: {},
    create: {
      id: "style-rule-1",
      userId: user.id,
      accountId: account.id,
      personaId: "founder-voice",
      type: "structure",
      ruleText: "前兩段內要給出結論與數字，不要先鋪抽象背景。",
      severity: "high"
    }
  });

  await prisma.antiAiRule.upsert({
    where: { id: "anti-ai-1" },
    update: {},
    create: {
      id: "anti-ai-1",
      userId: user.id,
      accountId: account.id,
      label: "禁止行銷空話",
      description: "避免輸出像簡報口號一樣的字詞。",
      pattern: "賦能|閉環|底層邏輯",
      severity: "medium",
      examples: ["賦能團隊", "完成閉環"]
    }
  });

  await prisma.researchAsset.upsert({
    where: { id: "research-1" },
    update: {},
    create: {
      id: "research-1",
      userId: user.id,
      accountId: account.id,
      sourceType: "competitor-teardown",
      title: "47 個同類帳號拆解",
      content: "教程、AI+變現、人設解析、醫學健康、資源合集是最穩的五類爆款。",
      sourceUrl: "https://example.com/teardown",
      topicTags: ["選題策略", "爆款結構"],
      structureNotes: "用分類法整理出高曝光題材與高書籤題材差異。",
      evidenceLevel: "high",
      reusable: true,
      saturationLabel: "medium"
    }
  });

  await prisma.insightCard.upsert({
    where: { id: "insight-1" },
    update: {},
    create: {
      id: "insight-1",
      userId: user.id,
      researchAssetId: "research-1",
      title: "高曝光不等於高漲粉",
      insightText: "教程穩拿曝光，但人設敘事更容易帶 follow 行為。",
      sourceLabel: "47 帳號拆解",
      angleLabel: "題目目標對齊",
      evidenceLevel: "high"
    }
  });

  await prisma.reusablePattern.upsert({
    where: { id: "pattern-1" },
    update: {},
    create: {
      id: "pattern-1",
      userId: user.id,
      label: "我做了 X，結果是 Y",
      patternType: "title",
      template: "我做了 {action}，{period} 後拿到 {result}",
      summary: "真實經歷 + 數字錨點 + 可複製路徑",
      bestFor: "高曝光教學 / 實戰拆解",
      lanes: ["實戰教程", "AI + 變現"]
    }
  });

  await prisma.topicCard.upsert({
    where: { id: "topic-1" },
    update: {},
    create: {
      id: "topic-1",
      userId: user.id,
      accountId: account.id,
      lane: "實戰教程",
      goal: "曝光",
      angle: "把 Obsidian + AI 串成一條可日更的內容產線",
      targetPlatform: "x-manual",
      evidenceRefs: ["research-1", "insight-1", "pattern-1"],
      score: 0.92,
      status: "ReadyToWrite",
      needsResearch: false,
      confidenceScore: 0.88,
      sourceType: "manual",
      missionTag: "AI內容系統"
    }
  });

  await prisma.operatingBrief.upsert({
    where: { id: "brief-1" },
    update: {},
    create: {
      id: "brief-1",
      userId: user.id,
      accountId: account.id,
      topicCardId: "topic-1",
      targetPlatform: "x-manual",
      targetOutcome: "曝光",
      audience: "想一人做內容又不想被 AI 味拖累的創作者",
      hookStrategy: "先給成績數字，再拆背後流程",
      ctaStrategy: "收藏這套系統，再按自己的工具改",
      whyNow: "你已經累積到足夠多長文案例，可以開始公開系統化方法。",
      assignment: "寫成一篇能被收藏的流程拆解文。",
      successMetric: "bookmark rate > 0.5%",
      retrievalNotes: "引用語料裡的數字化語氣，避免說教。"
    }
  });

  await prisma.draftAsset.upsert({
    where: { id: "draft-1" },
    update: {},
    create: {
      id: "draft-1",
      userId: user.id,
      accountId: account.id,
      briefId: "brief-1",
      topicCardId: "topic-1",
      postId: post.id,
      platform: "x-manual",
      structure: "Hook -> 系統全貌 -> 四層知識庫 -> 流程 -> 規則",
      body: "我不是突然變會寫。只是把選題、素材、草稿、配圖和復盤全部收進同一個系統。很多人會問這樣是不是太重，但真正厲害的人都在做這件事。",
      confidenceScore: 0.79,
      antiAiFlags: ["很多人會問", "真正厲害的人都在"],
      reviewLane: "review",
      status: "draft"
    }
  });

  await prisma.imageStylePreset.upsert({
    where: { slug: "tutorial-infographic" },
    update: {},
    create: {
      userId: user.id,
      name: "Tutorial Infographic",
      slug: "tutorial-infographic",
      description: "白底、淺色氣泡、圓角卡片與扁平圖標，適合工具與流程教學。",
      visualDirection: "clean hero banner",
      promptPrefix: "clean infographic, white background, soft accent bubbles, rounded cards, bold Chinese headline",
      aspectRatio: "16:9",
      defaultForLanes: ["實戰教程", "AI + 變現"]
    }
  });

  await prisma.imageStylePreset.upsert({
    where: { slug: "concept-poster" },
    update: {},
    create: {
      userId: user.id,
      name: "Concept Poster",
      slug: "concept-poster",
      description: "大字構圖、角色與文字咬合，適合觀點文與趨勢判讀。",
      visualDirection: "editorial poster",
      promptPrefix: "editorial poster, expressive typography, concept-driven, bold Chinese type",
      aspectRatio: "4:5",
      defaultForLanes: ["趨勢判讀", "人設敘事", "數據復盤"]
    }
  });

  await prisma.imageBrief.upsert({
    where: { id: "image-brief-1" },
    update: {},
    create: {
      id: "image-brief-1",
      userId: user.id,
      draftId: "draft-1",
      imageRole: "hero",
      stylePresetId: (await prisma.imageStylePreset.findUniqueOrThrow({ where: { slug: "tutorial-infographic" } })).id,
      prompt: "以 AI 內容飛輪為主題，畫出語料、素材、選題、起草、學習回寫的五段流程。",
      aspectRatio: "16:9",
      status: "pending"
    }
  });

  await prisma.performanceSignal.upsert({
    where: { id: "signal-1" },
    update: {},
    create: {
      id: "signal-1",
      userId: user.id,
      accountId: account.id,
      draftId: "draft-1",
      postId: post.id,
      contentId: "draft-1",
      platform: "x-manual",
      impressions: 120000,
      bookmarks: 920,
      follows: 156,
      ctr: 0.036,
      conversions: 18,
      likes: 4100,
      replies: 180,
      reposts: 260,
      quotes: 44,
      shares: 320,
      titlePattern: "我做了X，結果是Y",
      hasNumber: true,
      hasIdentity: false,
      isTutorial: true,
      hasCaseStudy: true,
      usesPersonaStory: false
    }
  });

  await prisma.learningRule.upsert({
    where: { id: "learning-1" },
    update: {},
    create: {
      id: "learning-1",
      userId: user.id,
      accountId: account.id,
      scope: "實戰教程",
      signalType: "high-bookmark",
      ruleText: "教程題只要帶具體數字與可複製步驟，書籤率通常明顯高於純觀點文。",
      weight: 0.84,
      isActive: true,
      lastValidatedAt: new Date()
    }
  });

  await prisma.titlePattern.upsert({
    where: { id: "title-1" },
    update: {},
    create: {
      id: "title-1",
      userId: user.id,
      label: "數字結果型",
      template: "我做了 {action}，{period} 後拿到 {result}",
      hasNumber: true,
      hasIdentity: false,
      hasContrast: false,
      expectedOutcome: "曝光"
    }
  });

  await prisma.hookPattern.upsert({
    where: { id: "hook-1" },
    update: {},
    create: {
      id: "hook-1",
      userId: user.id,
      label: "先成績再拆流程",
      template: "先講結果，再講為什麼不是能力問題，而是系統問題。",
      bestFor: "教程 / 系統拆解"
    }
  });

  await prisma.formatOutcome.upsert({
    where: { id: "format-1" },
    update: {},
    create: {
      id: "format-1",
      userId: user.id,
      label: "高曝光教程",
      lane: "實戰教程",
      metricFocus: "impressions",
      note: "最適合帶數字與流程圖。"
    }
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
