import { NextResponse } from "next/server";
import { authorizeCronRequest } from "@/lib/cron-auth";
import { prisma } from "@/lib/prisma";

export async function GET(request: Request) {
  const auth = await authorizeCronRequest(request);
  if (!auth.ok) return NextResponse.json({ ok: false }, { status: 401 });

  const drafts = await prisma.post.findMany({
    where: {
      status: "draft",
      contentType: "threads"
    },
    orderBy: { createdAt: "desc" },
    take: 8,
    select: {
      id: true,
      title: true,
      textContent: true,
      status: true,
      requiresApproval: true,
      approvalState: true,
      isAutoGenerated: true,
      createdAt: true,
      account: { select: { platformUsername: true } }
    }
  });

  return NextResponse.json({
    ok: true,
    drafts: drafts.map((d) => ({
      id: d.id,
      title: d.title ?? d.textContent?.slice(0, 60) ?? "（無標題）",
      preview: d.textContent?.slice(0, 120) ?? "",
      account: d.account.platformUsername,
      requiresApproval: d.requiresApproval,
      approvalState: d.approvalState,
      isAutoGenerated: d.isAutoGenerated,
      createdAt: d.createdAt.toISOString()
    }))
  });
}
