import { prisma } from "@/lib/prisma";

function stripHtml(html: string) {
  return html.replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
}

function extractTopicTag(title: string, text: string) {
  const source = `${title} ${text}`.toLowerCase();

  if (source.includes("audio")) {
    return "#audio";
  }

  if (source.includes("threads")) {
    return "#threads";
  }

  if (source.includes("growth")) {
    return "#growth";
  }

  return "#update";
}

function buildThreadsSummary(input: {
  title?: string | null;
  excerpt?: string | null;
  htmlContent?: string | null;
  platformUrl?: string | null;
}) {
  const title = input.title?.trim() ?? "新文章已上線";
  const body = input.excerpt?.trim() || stripHtml(input.htmlContent ?? "").slice(0, 220);
  const tag = extractTopicTag(title, body);
  const linkText = input.platformUrl ? `\n完整文章：${input.platformUrl}` : "";
  const draft = `${title}\n\n${body}${linkText}\n\n${tag}`.trim();

  return draft.length > 500 ? `${draft.slice(0, 497)}...` : draft;
}

export async function syncPostToThreads(postId: string) {
  const sourcePost = await prisma.post.findUnique({
    where: { id: postId },
    include: {
      account: true
    }
  });

  if (!sourcePost) {
    throw new Error("找不到指定貼文。");
  }

  if (sourcePost.account.platform !== "wordpress") {
    throw new Error("目前只支援將 WordPress 文章同步到 Threads。");
  }

  if (sourcePost.status !== "published") {
    throw new Error("請先讓 WordPress 文章成功發布後，再同步到 Threads。");
  }

  const threadsAccount = await prisma.platformAccount.findFirst({
    where: {
      platform: "threads",
      isActive: true,
      userId: sourcePost.userId
    },
    orderBy: [{ lastSyncedAt: "desc" }, { createdAt: "desc" }]
  });

  if (!threadsAccount) {
    throw new Error("還沒有可用的 Threads 帳號，請先完成 Threads 連接。");
  }

  const existing = await prisma.post.findFirst({
    where: {
      accountId: threadsAccount.id,
      replyToPostId: sourcePost.platformPostId,
      textContent: {
        startsWith: "【Blog Sync】"
      }
    }
  });

  if (existing) {
    return {
      postId: existing.id,
      scheduled: existing.status === "scheduled",
      duplicated: true
    };
  }

  const summary = buildThreadsSummary(sourcePost);
  const created = await prisma.post.create({
    data: {
      userId: sourcePost.userId,
      accountId: threadsAccount.id,
      contentType: "text",
      textContent: `【Blog Sync】\n${summary}`,
      status: "scheduled",
      scheduledAt: new Date(),
      replyToPostId: sourcePost.platformPostId,
      isAutoGenerated: false
    }
  });

  await prisma.automationLog.create({
    data: {
      accountId: threadsAccount.id,
      postId: created.id,
      actionType: "threads_sync",
      status: "scheduled",
      detail: "已由 WordPress 文章建立 Threads 摘要佇列"
    }
  });

  return {
    postId: created.id,
    scheduled: true,
    duplicated: false
  };
}
