import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

function buildManualReply(match: { authorUsername: string; postText: string }, keyword: string) {
  return `嗨 ${match.authorUsername}，看到你提到 ${keyword}。我們已經記下這個回覆，後續會再整理更完整的內容給你。`;
}

export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const { id } = await params;
    const match = await prisma.keywordMatch.findUnique({
      where: { id },
      include: {
        keyword: true,
        account: true
      }
    });

    if (!match) {
      return NextResponse.json({ ok: false, message: "找不到命中紀錄" }, { status: 404 });
    }

    const accountId = match.accountId;

    if (!accountId || !match.account || match.account.platform !== "threads") {
      return NextResponse.json({ ok: false, message: "目前僅支援 Threads 命中的快速回覆" }, { status: 400 });
    }

    const { getPlatformAdapter } = await import("@/lib/platforms");
    const adapter = getPlatformAdapter("threads");
    const text = buildManualReply(match, match.keyword.keyword);
    const result = await adapter.replyToPost(accountId, match.platformPostId, text);

    const post = await prisma.post.create({
      data: {
        userId: match.account.userId,
        accountId,
        contentType: "text",
        textContent: text,
        status: "published",
        publishedAt: new Date(),
        platformPostId: result.platformPostId,
        platformUrl: result.url ?? null,
        replyToPostId: match.platformPostId,
        sourceMatchId: match.id,
        isAutoGenerated: false
      }
    });

    await prisma.keywordMatch.update({
      where: { id: match.id },
      data: {
        actionTaken: "manual_reply",
        actionPostId: post.id
      }
    });

    await prisma.automationLog.create({
      data: {
        matchId: match.id,
        accountId,
        postId: post.id,
        actionType: "reply",
        status: "executed",
        detail: "已透過快速動作手動回覆"
      }
    });

    return NextResponse.json({ ok: true, message: "已送出快速回覆", postId: post.id });
  } catch (error) {
    return NextResponse.json(
      {
        ok: false,
        message: error instanceof Error ? error.message : "Quick reply failed"
      },
      { status: 400 }
    );
  }
}
